//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean InteractUI
        {
            get
            {
                return SteamVR_Actions.default_InteractUI;
            }
        }
        
        public virtual SteamVR_Action_Boolean Teleport
        {
            get
            {
                return SteamVR_Actions.default_Teleport;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabPinch
        {
            get
            {
                return SteamVR_Actions.default_GrabPinch;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabGrip
        {
            get
            {
                return SteamVR_Actions.default_GrabGrip;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.default_Pose;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonRightHand;
            }
        }
        
        public virtual SteamVR_Action_Single Squeeze
        {
            get
            {
                return SteamVR_Actions.default_Squeeze;
            }
        }
        
        public virtual SteamVR_Action_Boolean HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.default_HeadsetOnHead;
            }
        }
        
        public virtual SteamVR_Action_Boolean SnapTurnLeft
        {
            get
            {
                return SteamVR_Actions.default_SnapTurnLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean SnapTurnRight
        {
            get
            {
                return SteamVR_Actions.default_SnapTurnRight;
            }
        }
        
        public virtual SteamVR_Action_Boolean SwitchCamLeft
        {
            get
            {
                return SteamVR_Actions.default_SwitchCamLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean SwitchCamRight
        {
            get
            {
                return SteamVR_Actions.default_SwitchCamRight;
            }
        }
        
        public virtual SteamVR_Action_Boolean ToggleCamCanvas
        {
            get
            {
                return SteamVR_Actions.default_ToggleCamCanvas;
            }
        }
        
        public virtual SteamVR_Action_Boolean Accept
        {
            get
            {
                return SteamVR_Actions.default_Accept;
            }
        }
        
        public virtual SteamVR_Action_Boolean Deny
        {
            get
            {
                return SteamVR_Actions.default_Deny;
            }
        }
        
        public virtual SteamVR_Action_Boolean TogglePathVisual
        {
            get
            {
                return SteamVR_Actions.default_TogglePathVisual;
            }
        }
        
        public virtual SteamVR_Action_Boolean StopDrone
        {
            get
            {
                return SteamVR_Actions.default_StopDrone;
            }
        }
        
        public virtual SteamVR_Action_Boolean MarkDefect
        {
            get
            {
                return SteamVR_Actions.default_MarkDefect;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_Haptic;
            }
        }
    }
}
